apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: hello-world
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: http://argocd-parameters-charts
        chart: hello-world
        targetRevision: 0.1.0
        helm:
          parameters: []
      destination:
        server: https://kubernetes.default.svc
        namespace: hello-world
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
